#:schema node_modules/wrangler/config-schema.json
name = "sledge-edge"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "settings", id = "e7f9463c51a747ed9ef9c2909a95283e" }
]